name: auto prettier

on:
  push:
    paths:
      - 'site/**'

jobs:
  prettier:
    runs-on: nitro-2C8G

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      
      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --config ./site/.prettierrc.json --ignore-path ./site/.prettierignore  --write ./site